#!/bin/zsh
set -euo pipefail

script_dir=${0:A:h}
project_root=${script_dir:h}
source "${script_dir}/dart_engine_env.sh"

fail() {
  print -u2 "Dart Engine bootstrap error: $1"
  exit 1
}

usage() {
  cat <<'EOF'
Usage: ./scripts/bootstrap_dart_engine.sh

Downloads the complete Dart checkout at the SDK revision pinned by this
project, syncs its build dependencies, builds dart_engine_jit_shared, validates
the dylib, and writes .dart_tool/dart-engine/env.zsh.

Optional environment overrides:
  DART_SDK               Released Dart SDK root.
  DART_ENGINE_WORKSPACE  gclient workspace (default: .dart_tool/dart-engine).
  DART_ENGINE_ROOT       Dart sdk checkout inside that workspace.
EOF
}

if (( $# > 1 )); then
  usage >&2
  exit 64
fi
if (( $# == 1 )); then
  if [[ "$1" != "-h" && "$1" != "--help" ]]; then
    usage >&2
    exit 64
  fi
  usage
  exit 0
fi

[[ $(uname -s) == Darwin ]] || fail "the AppKit Engine build requires macOS"
[[ -n "${DART_SDK:-}" ]] || fail "DART_SDK is unset and dart is not on PATH"
[[ -f "${DART_SDK}/version" ]] || fail "missing ${DART_SDK}/version"
[[ -f "${DART_SDK}/revision" ]] || fail "missing ${DART_SDK}/revision"

sdk_version=$(<"${DART_SDK}/version")
sdk_revision=$(<"${DART_SDK}/revision")
[[ "${sdk_version}" == "${DART_APPKIT_PINNED_DART_VERSION}" ]] || \
  fail "expected Dart ${DART_APPKIT_PINNED_DART_VERSION}, found ${sdk_version}"
[[ "${sdk_revision}" == "${DART_APPKIT_PINNED_DART_REVISION}" ]] || \
  fail "SDK revision ${sdk_revision} does not match pinned revision ${DART_APPKIT_PINNED_DART_REVISION}"

gclient_executable=$(command -v gclient 2>/dev/null || true)
[[ -n "${gclient_executable}" ]] || \
  fail "gclient is required; install depot_tools and add it to PATH"
command -v git >/dev/null 2>&1 || fail "git is required"
command -v xcrun >/dev/null 2>&1 || fail "Xcode command-line tools are required"

workspace=${DART_ENGINE_WORKSPACE:A}
engine_root=${DART_ENGINE_ROOT:A}
[[ "${engine_root:t}" == sdk ]] || \
  fail "DART_ENGINE_ROOT must be the sdk directory inside the gclient workspace"
[[ "${engine_root:h}" == "${workspace}" ]] || \
  fail "DART_ENGINE_ROOT must equal DART_ENGINE_WORKSPACE/sdk"

available_kib=$(df -Pk "${project_root}" | awk 'NR == 2 { print $4 }')
if [[ -n "${available_kib}" ]] && (( available_kib < 15728640 )); then
  print -u2 "Warning: less than 15 GiB is free; the Dart checkout and release build may not fit."
fi

mkdir -p "${workspace}"
if [[ ! -f "${workspace}/.gclient" ]]; then
  [[ ! -e "${engine_root}" ]] || \
    fail "${engine_root} exists but ${workspace}/.gclient does not; refusing to replace it"
  print "Configuring official Dart checkout in ${workspace}"
  (
    cd "${workspace}"
    "${gclient_executable}" config \
      --name=sdk \
      --managed \
      --custom-var=download_reclient=False \
      "${DART_APPKIT_DART_REPOSITORY}"
  )
else
  gclient_configuration=$(<"${workspace}/.gclient")
  [[ "${gclient_configuration}" == *"${DART_APPKIT_DART_REPOSITORY}"* ]] || \
    fail "${workspace}/.gclient does not configure the official Dart repository"
fi

if [[ -d "${engine_root}/.git" ]]; then
  existing_origin=$(git -C "${engine_root}" remote get-url origin 2>/dev/null || true)
  [[ "${existing_origin}" == "${DART_APPKIT_DART_REPOSITORY}" || \
     "${existing_origin}" == "${DART_APPKIT_DART_REPOSITORY%.git}" ]] || \
    fail "unexpected existing Dart origin: ${existing_origin}"
  tracked_changes=$(git -C "${engine_root}" status --porcelain --untracked-files=no)
  [[ -z "${tracked_changes}" ]] || \
    fail "the Dart checkout has tracked local changes; preserve or revert them before syncing"
fi

print "Syncing Dart and build dependencies at ${sdk_revision}"
(
  cd "${workspace}"
  "${gclient_executable}" sync \
    --revision="sdk@${sdk_revision}" \
    --no-history
)

[[ -d "${engine_root}/.git" ]] || fail "gclient did not create ${engine_root}"
engine_revision=$(git -C "${engine_root}" rev-parse HEAD 2>/dev/null || true)
[[ "${engine_revision}" == "${sdk_revision}" ]] || \
  fail "checkout revision ${engine_revision} does not match ${sdk_revision}"

origin_url=$(git -C "${engine_root}" remote get-url origin 2>/dev/null || true)
[[ "${origin_url}" == "${DART_APPKIT_DART_REPOSITORY}" || \
   "${origin_url}" == "${DART_APPKIT_DART_REPOSITORY%.git}" ]] || \
  fail "unexpected Dart origin: ${origin_url}"

print "Verified Dart checkout revision ${engine_revision}"
"${script_dir}/build_dart_engine.sh"
"${script_dir}/check_dart_engine.sh"

environment_file="${workspace}/env.zsh"
environment_tmp="${environment_file}.tmp.$$"
{
  print -r -- "# Generated by scripts/bootstrap_dart_engine.sh."
  print -r -- "export DART_SDK=${(q)DART_SDK}"
  print -r -- "export DART_ENGINE_WORKSPACE=${(q)workspace}"
  print -r -- "export DART_ENGINE_ROOT=${(q)engine_root}"
  print -r -- "export DART_ENGINE_LIBRARY=${(q)DART_ENGINE_LIBRARY}"
  print -r -- "export DART_ENGINE_KERNEL_COMPILER=${(q)DART_ENGINE_KERNEL_COMPILER}"
  print -r -- "export DART_ENGINE_PLATFORM=${(q)DART_ENGINE_PLATFORM}"
} > "${environment_tmp}"
mv "${environment_tmp}" "${environment_file}"

print "Dart Engine bootstrap completed"
print "  checkout: ${engine_root}"
print "  revision: ${engine_revision}"
print "  library: ${DART_ENGINE_LIBRARY}"
print "  optional shell environment: source ${environment_file}"
